### ISSUE TITLE
Error Listing the SQLITE DATABASES using csd list command

### ISSUE THREAD

**Issue by mainakanyi** [justinlettau/cordova-sqlite-devtools#1]
C:\xampp\htdocs\ionicLogin>csd list
{ Error: Command failed: adb shell "run-as com.ionicframework.ioniclogin429431 ls databases"
'adb' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'adb shell "run-as com.ionicframework.ioniclogin429431 ls databases"' }

**Comment by justinlettau** [comment]
Make sure you have Android SDK installed and `adb` added to your Windows System PATH variable. Instructions can be found here: http://www.howtogeek.com/125769/how-to-install-and-use-abd-the-android-debug-bridge-utility/

**Comment by mainakanyi** [comment]
@justinlettau csd --help works well. I already added the adb to the system path.  What might be another problem.

**Comment by justinlettau** [comment]
Can you run `adb devices` in command prompt successfully?

**Comment by mainakanyi** [comment]
Yes.
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Jkanyi>adb devices
List of devices attached
42032358bc939100        device


C:\Users\Jkanyi>adb devices
List of devices attached
42032358bc939100        device


C:\Users\Jkanyi>csd --help

  Usage: csd [options] [command]


  Commands:

    list|ls            List all database files.
    pull|p [database]  Pull database from device.
    clean|c            Remove all backup sqlite files.

  Options:

    -h, --help     output usage information
    -V, --version  output the version number


C:\Users\Jkanyi>csd list
{ Error: ENOENT: no such file or directory, open 'C:\Users\Jkanyi\config.xml'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Jkanyi\\config.xml' }

C:\Users\Jkanyi>

**Comment by justinlettau** [comment]
Are you running `csd list` from your Cordova project directory?

**Comment by mainakanyi** [comment]
Yes, this is my ionic folder

C:\xampp\htdocs\ionicLogin>csd --help

  Usage: csd [options] [command]


  Commands:

    list|ls            List all database files.
    pull|p [database]  Pull database from device.
    clean|c            Remove all backup sqlite files.

  Options:

    -h, --help     output usage information
    -V, --version  output the version number


C:\xampp\htdocs\ionicLogin>csd list
run-as: Package 'com.ionicframework.ioniclogin429431' is unknown


C:\xampp\htdocs\ionicLogin>

**Comment by justinlettau** [comment]
Is the app (com.ionicframework.ioniclogin429431) installed on your device, and debuggable?

**Comment by mainakanyi** [comment]
@justinlettau where should I make it debuggable? I am using ionic 2.

**Comment by justinlettau** [comment]
Make sure you can remote debug: https://ionicframework.com/docs/v2/resources/developer-tips/#debugging-android-chrome

**Comment by mainakanyi** [comment]
Already done that. What does this error mean?

run-as: Package 'com.ionicframework.ioniclogin429431' is unknown

**Comment by justinlettau** [comment]
Seems to be an `adb` issue: https://code.google.com/p/android/issues/detail?id=58373
