### ISSUE TITLE
Please Enter the key used to encrypt the database? 

### ISSUE THREAD

**Issue by mainakanyi** [justinlettau/cordova-sqlite-devtools#3]
I managed to pull the database from the phone, but when open it through DB Browser for sqlite, I get the prompt. Please Enter the key used to encrypt the database? 

I didn't put any password. How can I solve it. Thanks

**Comment by justinlettau** [comment]
The database file being encrypted seems to be a byproduct of the adb functions used under the hood. I'll have to look into this a bit more.

**Comment by justinlettau** [comment]
Fixed in v1.0.0!
